site_name: Prunejuice Documentation
site_description: Parallel agentic coding workflow orchestrator
site_url: https://your-username.github.io/prunejuice/
repo_url: https://github.com/your-username/prunejuice
repo_name: your-username/prunejuice
site_dir: docs-build

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Quickstart:
    - New Project: quickstart/new-project.md
    - Existing Project: quickstart/existing-project.md
    - First Action: quickstart/first-action.md
  - Guides:
    - Action Definition: guides/action-definition.md
    - Step Creation: guides/step-creation.md
    - Project Setup: guides/project-setup.md
    - Workflows: guides/workflows.md
  - Concepts:
    - Worktrees: concepts/worktrees.md
    - Sessions: concepts/sessions.md
    - Architecture: concepts/architecture.md
  - Reference:
    - Action: reference/action.md
    - Configuration: reference/config.md
    - YAML Schema: reference/yaml-schema.md
  - Advanced:
    - Custom Integrations: advanced/custom-integrations.md
    - MCP Server: advanced/mcp-server.md
    - Troubleshooting: advanced/troubleshooting.md